### ISSUE TITLE
Stub out basics of the module

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/field_encrypt#1]
Use Drupal console for the following:
1. info file, dependency to encrypt
2. module file stubbing out entity presave and load hooks
3. src/Tests and a placeholder simpletest
4. .travis.yml (can copy basics from another module)
5. readme.md with basics stubbed out

**Comment by damontgomery** [comment]
I have the basic version of this module working. You can assign fields to use encryption and basic fields can be encrypted and decrypted.

TODO:
- Work with more complex fields
- Refactor code to use a field encryption service rather than a hook
- Batch process fields when the field storage setting is changed
- Tests
- Cleanup
- Documentation
- .travis.yml

I will continue to work on this tomorrow.

**Comment by nerdstein** [comment]
awesome progress! 

Feel free to submit a PR for code review

**Comment by nerdstein** [comment]
Whoops, nevermind. Just saw you pushed it up.

**Comment by damontgomery** [comment]
Split the remaining tasks into their own issues.
